components:
  schemas:
    AuthUser:
      properties:
        id:
          example: nilsmf
          type: string
        pwd:
          description: Hashed password
          type: string
      required:
      - id
      - pwd
      type: object
    Email:
      description: Email struct, an email is verified to be existing and valid.
      type: string
    Runtime:
      description: Runtime of a service
      properties:
        date:
          description: Date the service started
          example: 11.03.24 [16:34]
          type: string
        time:
          description: Time since epoch, in milliseconds
          example: '69420'
          minimum: 0
          type: integer
      required:
      - date
      - time
      type: object
    User:
      properties:
        email:
          $ref: '#/components/schemas/Email'
        id:
          description: User identity
          type: string
        iid:
          description: Internal ID, used in databases
          minimum: 0
          type: integer
      required:
      - iid
      - id
      - email
      type: object
    Version:
      description: Semver
      properties:
        major:
          example: '4'
          minimum: 0
          type: integer
        minor:
          example: '2'
          minimum: 0
          type: integer
        patch:
          example: '0'
          minimum: 0
          type: integer
      required:
      - major
      - minor
      - patch
      type: object
info:
  description: 'nilsmf-lib: Component Specification'
  license:
    name: ''
  title: nilsmf-lib
  version: 1.1.3
openapi: 3.0.3
paths:
  /:
    get:
      operationId: empty
      responses:
        '200':
          description: IGNORE
      tags:
      - crate
